# Generated by Django 5.2 on 2025-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Brief summary of the post", max_length=200
            ),
        ),
    ]
