# Generated by Django 5.2 on 2025-05-02 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                help_text="Main content of the blog post",
                validators=[django.core.validators.MinLengthValidator(200)],
            ),
        ),
    ]
