# Generated by Django 5.2 on 2025-05-03 10:39

import django.core.validators
import django.db.models.deletion
import web_apis.contact.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="International format preferred",
                        max_length=20,
                        null=True,
                        validators=[
                            web_apis.contact.models.Contact.validate_international_phone_number
                        ],
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("either", "Either"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("message_content", models.TextField()),
                (
                    "privacy_policy_accepted",
                    models.BooleanField(
                        default=False, help_text="Required to submit the form"
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer_url", models.URLField(blank=True, null=True)),
                (
                    "browser_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "captcha_token",
                    models.CharField(
                        help_text="CAPTCHA verification token to prevent spam submissions",
                        max_length=1000,
                    ),
                ),
                ("captcha_verified", models.BooleanField(default=False)),
                ("captcha_verified_at", models.DateTimeField(blank=True, null=True)),
                ("recaptcha_score", models.FloatField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=web_apis.contact.models.upload_contact_attachment_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            ),
                            django.core.validators.MaxValueValidator(10485760),
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contact.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Attachment",
                "verbose_name_plural": "Contact Attachments",
            },
        ),
    ]
