# Generated by Django 5.2 on 2025-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "USER"),
                    ("admin", "ADMIN"),
                    ("moderator", "MODERATOR"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
