# Generated by Django 5.2 on 2025-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("individual", "Individual"),
                            ("payment", "Payment"),
                            ("user", "User"),
                            ("profile", "Profile"),
                            ("morphpix", "MorphPix"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_update", models.BooleanField(default=False)),
                ("shutdown_message", models.TextField(blank=True, null=True)),
                ("update_message", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Manager",
                "verbose_name_plural": "App Managers",
            },
        ),
        migrations.CreateModel(
            name="GlobalAppControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_global_shutdown", models.BooleanField(default=False)),
                ("global_shutdown_message", models.TextField(blank=True, null=True)),
                ("is_global_update", models.BooleanField(default=False)),
                ("global_update_message", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global App Control",
                "verbose_name_plural": "Global App Controls",
            },
        ),
    ]
