# Generated by Django 5.2 on 2025-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in US Dollars", max_digits=10
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this price is currently active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Price",
                "verbose_name_plural": "Subscription Prices",
            },
        ),
    ]
