# Generated by Django 5.2 on 2025-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
